FROM ubuntu

RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
RUN sleep 10
